/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUserFromDiscriminatorValue } from '../models/index.js';
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = '{+baseurl}/me';
/**
 * Metadata for all the requests in the request builder.
 */
export const MeRequestBuilderRequestsMetadata = {
  get: {
    uriTemplate: MeRequestBuilderUriTemplate,
    responseBodyContentType: 'application/json',
    adapterMethodName: 'send',
    responseBodyFactory: createUserFromDiscriminatorValue,
  },
};
/* tslint:enable */
/* eslint-enable */
//# sourceMappingURL=index.js.map
